# Generated by Django 4.2.4 on 2023-08-04 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "account_number",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=10,
                        max_length=15,
                        prefix="151",
                        unique=True,
                    ),
                ),
                (
                    "account_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=10,
                        max_length=14,
                        prefix="EG",
                        unique=True,
                    ),
                ),
                (
                    "pin_number",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=4,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "ref_code",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234567890",
                        length=7,
                        max_length=10,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        default="EG", max_length=2, unique=True
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("active", "Active"), ("in-active", "In-Active")],
                        default="in-active",
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("kyc_submitted", models.BooleanField(default=False)),
                ("kyc_confirmed", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=15
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("national_id_card", "National Id Card"),
                            ("passport", "Passport"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="recommended_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
