# Generated by Django 4.2.4 on 2023-08-04 13:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="nationality",
            field=django_countries.fields.CountryField(default="EG", max_length=2),
        ),
    ]
