# Generated by Django 4.2.4 on 2023-08-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_alter_account_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("image", models.ImageField(default="default.jpg", upload_to="kyc")),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("married", "Married"),
                            ("single", "Single"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=15
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("national_id_card", "National Id Card"),
                            ("passport", "Passport"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("signature", models.ImageField(upload_to="kyc")),
                (
                    "country",
                    django_countries.fields.CountryField(default="EG", max_length=2),
                ),
                ("state", models.TextField()),
                ("city", models.TextField()),
                ("mobile", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
