# Generated by Django 4.2.4 on 2023-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_kyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="identity_image",
            field=models.ImageField(blank=True, null=True, upload_to="kyc"),
        ),
    ]
