# Generated by Django 4.2.4 on 2023-08-04 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_kyc_identity_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.account",
            ),
        ),
    ]
