# Generated by Django 4.2.4 on 2023-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_kyc_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="city",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
