# Generated by Django 4.2.4 on 2023-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_kyc_city_alter_kyc_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("in-active", "In-Active"),
                ],
                default="in-active",
                max_length=50,
            ),
        ),
    ]
